### ISSUE TITLE
[Preferences] Remove the name option from the settings page and replace with FTP credential options.

### ISSUE THREAD

**Issue by cheeseburgur101** [FRC2706/MCMergeManager#86] opened 2017-02-04 21:10 UTC
- [x] Remove NotificationPreferenceFragment
- [x] Remove "Team Name"
- [x] Add "FTP Server Address" --> defaults to "ftp.team2706.ca" ?
- [x] Add "FTP Account" --> defaults to "scout" ?
- [x] Add "FTP Passwd" --> defaults to empty?
- [x] Add "DB Server Address" --> defaults to "ftp.team2706.ca" ?
- [x] Add "Sync Photos Over Data Plan" --> defaults to No.
- [x] Add code to MainActivity.onResume() that checks the SharedPreference "Sync Photos Over Data Plan", checks the device WiFi status, and disables the "Sync Photos" button.
- [x] Make sure unused preference keys are removed from strings.xml
- [x] Update local file structure that's created in `FileUtils.checkLocalFileStructure()`

Working branch: FTP_integration

**Comment by ounsworth** [comment] 2017-02-04 21:19
Dupe of #87

**Comment by ounsworth** [comment] 2017-02-06 13:20
I'm gonna reopen this because I prefer using student-made tickets.

**Comment by ounsworth** [comment] 2017-02-10 15:49
Nathan, I see you've checked off some stuff. I went looking for the code but which branch did you check it in to?

**Closed** 2017-02-19 20:24 UTC
